### ISSUE TITLE
Download files via links in terminal

### ISSUE THREAD

**Issue by anshumanv** [Anshuman-Verma/chia-anime-mass-downloader#1]
The current app grabs the links for an anime and isn't able to download them, probably adding a download helper like aria2 will help us to download episodes grabbed from the links.

**Comment by Yureien** [comment]
I'll like to do this! (Also, this is the 5th anime scraper I'm working on :P)

**Comment by anshumanv** [comment]
Thanks for showing interest here @FadedCoder , please go for it !

**Comment by anshumanv** [comment]
@FadedCoder you seem experienced to web-scrapers (and to anime as well 😆 ), would you like to become a collaborator to this project ?

**Comment by abhish311** [comment]
I would like to be a collaborator in this project, have resolved all three issues.Should I push?

**Comment by anshumanv** [comment]
@FadedCoder is already working on this, please collaborate with him when he sends a PR, will add you as collab after you contribute here well.

**Comment by FadedCoder** [comment]
My PRs are nearly ready. Just waiting for the PR for #2. I will then make the necessary changes and push it.

**Comment by Yureien** [comment]
@zuik Are you still working on this? Or should I push a PR and close your PR?

**Comment by anshumanv** [comment]
Please push a PR if you're done @FadedCoder

**Comment by zuik** [comment]
I haven't had time to work on this. If you work on it feels free to close
this PR
