### ISSUE TITLE
Add setup.py

### ISSUE THREAD

**Issue by wyj1026** [Anshuman-Verma/chia-anime-mass-downloader#11]
Hi, I'm considering add a setup.py to this repo, so we can use `chia-anime-downloader search ***` in every directory of terminal instead of using `python chia-anime-downloader.py search blah` in the .py file directory.
Any suggestions?
May I work on it?

**Comment by Yureien** [comment]
Yeah sure, that way we can make it into a pip repo.

**Comment by anshumanv** [comment]
This will really be great ! 👍 
Please do send a PR @wyj1026 😄

**Comment by wyj1026** [comment]
I've done this, but there is a preblem we need to discuss:
It is not recommended to use '-'  in the source code,  see https://www.python.org/dev/peps/pep-0008/#package-and-module-names and it will cause an error if we import it in other module. So it will be better if we change the file name
to chia_anime_downloader.py.
I'll send a PR if you agree to change it.   :)

**Comment by anshumanv** [comment]
Thanks for the link @wyj1026 , Please send a PR 😄

**Comment by Yureien** [comment]
Closing as issue is resolved.
