### ISSUE TITLE
Compatibility with Python 3.6.x

### ISSUE THREAD

**Issue by olaban-ji** [Anshuman-Verma/chia-anime-mass-downloader#18]
Those this script work flawlessly with python 3.x versions..@anshumanv @fadedcoder

**Comment by anshumanv** [comment]
Glad to see that you're interested, what's the issue @rawdpiper ?

**Comment by olaban-ji** [comment]
I'm more than interested, I'm so excited that I found this repository. I have python 2.7 installed on my PC, but whwnever I run the script I get Invalid Syntax. Does this mean that the script only works with Python 3.x?

Keep up the good work.

**Comment by anshumanv** [comment]
Yeah, unfortunately the script only support python 3.x :worried:

**Comment by olaban-ji** [comment]
Ok. Guess it's time to install python 3.x..

Keep up the good work bro.

**Comment by anshumanv** [comment]
Thanks for checking out the repo, really appreciate it. :smile:

**Comment by anshumanv** [comment]
>Ok. Guess it's time to install python 3.x..

Probably you can go ahead and send a PR for compatibility with python 2.7 :wink: @rawdpiper

**Comment by olaban-ji** [comment]
I'm not much of a programmer, still an amateur 😞

**Comment by anshumanv** [comment]
You can still learn stuff. :wink: @rawdpiper
