### ISSUE TITLE
Clean the script to make it more readable

### ISSUE THREAD

**Issue by anshumanv** [Anshuman-Verma/chia-anime-mass-downloader#2]
The current script is messed up, we can split them to individual functions and add docstrings as well.

**Comment by NikolaJankovic** [comment]
Working on this now!

**Comment by anshumanv** [comment]
Thanks !

**Comment by Yureien** [comment]
A request, please make this 4 spaces tab. The 8 spaces tab messes up my system.

**Comment by anshumanv** [comment]
Is it 8 ? Damn, 8 is too much 😞

**Comment by Yureien** [comment]
Yeah. It is showing 8 on my system. By the way do use Windows/Mac? The tabs are really messed up in my system.

**Comment by NikolaJankovic** [comment]
Will do

**Comment by anshumanv** [comment]
I use linux majorly and sometimes windows, but this project i did on windows i think @FadedCoder, code current;y looks ugly and has messed up indentation/spacing/newlines, hence opened this.

**Comment by NikolaJankovic** [comment]
There are also a number issues with the code when it's run on different platforms, for example the parser that bs4 uses for lxml has issues when run on osx (and maybe linux). I'm resolving all of this now, I'll have a pull request soon.

**Comment by anshumanv** [comment]
Thanks so much for you hard work @NikolaJankovic 👍

**Comment by Yureien** [comment]
I guess this issue should be closed, @anshumanv?

**Comment by anshumanv** [comment]
Thanks for the reminder @FadedCoder
