### ISSUE TITLE
Prevent those quality of videos from downloading that are not present

### ISSUE THREAD

**Issue by Yureien** [Anshuman-Verma/chia-anime-mass-downloader#3]
While fixing issue #1, I found that those episodes that don't have a specific quality available (see example below), don't output their links. Neither do they show any errors.

Example -

Search for "shiki" and choose 1080p.

**Comment by Yureien** [comment]
@anshumanv Can you add the appropriate labels to this? Thanks!

Also, I will solve this issue first, then issue #1.

**Comment by anshumanv** [comment]
Thanks for checking that out for me @FadedCoder !
Please do appropriately.

**Comment by anshumanv** [comment]
@FadedCoder is this done ?

**Comment by Yureien** [comment]
@anshumanv Nearly done, but I'm facing some weird server issues rn. Does the website ban the user for too many searches? Because it's acting weird for me.

**Comment by anshumanv** [comment]
I'm not sure about that since I never faced it.

**Comment by Yureien** [comment]
I'm pushing the PR. Please test it on your side too.

**Comment by anshumanv** [comment]
Sure thing 👍

**Comment by Yureien** [comment]
I made a weird discovery (found a new bug). All episodes don't have the same qualities available. This is what was causing the problem in my code. To reproduce this bug, please search for "Charlotte", and use "save them for later". When I used 1080p, only episode 12 had that quality. When I used 480p, all episodes except 8 had that one.

I'm looking into a way to fix this, but this might take some time :/

**Comment by Yureien** [comment]
I have an idea in mind: If the user, let's say, chooses 1080p, but only 720p is available, it will be automatically downgraded to 720p, and a WARNING message will be printed. Similarly, if the user chose 720p but it wasn't available, it will get downgraded to 360p.

This idea ensures no weird bugs, and will downgrade to the nearest quality next to the chosen one, while informing the user.

@anshumanv if you are okay with this idea, please tell so. I will make the PR for the same tomorrow.

**Comment by anshumanv** [comment]
This will work well, please send a PR

**Comment by olaban-ji** [comment]
@anshumanv @fadedcoder

If I were to select 360p video quality for a particular anime and one of the episodes of the anime doesn't have a video quality of a 360p but it has that of either 480p, 720p or 1080p, will the video quality be upgraded for that episode?

**Comment by anshumanv** [comment]
I think every episode has 360p available, if not, can you find me an episode which doesn't have a 360p but only higher quality, I think we assumed that every episode has 360p :sweat_smile:

**Comment by olaban-ji** [comment]
http://download.animepremium.tv/video/96222
http://download.animepremium.tv/video/96141
http://download.animepremium.tv/video/96059

**Comment by olaban-ji** [comment]
@anshumanv

Those are the links for the three latest episodes of one piece in the previous comment above They only have one quality option which is 720p.

**Comment by zsen-njsmi** [comment]
@anshumanv 
Hi, I tested the soup.find_all(rel="nofollow") on the animepremium site but no quality is being provided, 
result is `[<a class="bttn red right large" href="#" id="GO Report!!" rel="nofollow" title="Logout">Report</a>]`
Is there another way to get the quality? awesome app btw :D

**Comment by anshumanv** [comment]
Hey @bnu123 thanks for checking this out 😄 , I'm afraid I'm not maintaining this right now, will jump back if I fix something. 👍
