### ISSUE TITLE
Add argsparse

### ISSUE THREAD

**Issue by zuik** [Anshuman-Verma/chia-anime-mass-downloader#7]
I would like to add arguments to calling the script so that you can call it with argument instead of reading it in as input?

Something like `python chia-anime-downloader.py search blah` 

Could I work on it?
What do you think about it?

**Comment by anshumanv** [comment]
Hey @zuik !
Sure, go ahead.
Also do you think you can incorporate changes done in #4 which provided download support and all ?

**Comment by anshumanv** [comment]
#8 merged.
